apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
  labels:
    app: room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      name: room
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: room:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb-service:27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "meet"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "room"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: room-service
spec:
  type: NodePort
  selector:
    app: room
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080